### ISSUE TITLE
Make Commands Less Strict .100 pts

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-android-smoke-signals#10]
For example "//Joke " will not work because there is a space after.

~100 points

W16 ok!

**Comment by Tektonbuilds** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/15).
