### ISSUE TITLE
Replace depreciated code with new code. 100 pts

### ISSUE THREAD

**Issue by Tektonbuilds** [UCSB-CS56-Projects/cs56-android-smoke-signals#12]
When android OS updates, they often group together functions that do similar things or improve functions in such a way that it makes their previous functions pretty obsolete. This may cause some errors with phones that may have newer OSs that want to run the app. 

Replacing depreciated code takes a bit of research and comprehension of the code itself, so save this issue for after you learned how the code works.

Estimated: 100 pts

**Comment by Tektonbuilds** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/19).
