### ISSUE TITLE
Alert user if command not recognized

### ISSUE THREAD

**Issue by thatonesimon** [UCSB-CS56-Projects/cs56-android-smoke-signals#16]
For //SMS, //Contact, and //Powersave if user does not send enough arguments, text user back with detailed instructions on how to property use the command. 

Possibly send user the //Help text if there is an unrecognized command (ex. typo like //Locatoin).

**Comment by jimmylle** [comment]
F16 OK (150 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/21).
