### ISSUE TITLE
Make adding numbers to whitelist less strict

### ISSUE THREAD

**Issue by thatonesimon** [UCSB-CS56-Projects/cs56-android-smoke-signals#17]
Currently, the whitelist will only recognize integers (i.e. no parentheses, no spaces).

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/21).
