### ISSUE TITLE
Add a toggle to switch all features on or off

### ISSUE THREAD

**Issue by thatonesimon** [UCSB-CS56-Projects/cs56-android-smoke-signals#18]
Add a reset settings option that switches all settings to a certain state, so users don't have to set them individually (users can still change individual feature settings after using reset settings)

**Comment by jimmylle** [comment]
F16 OK (100 pts)

**Comment by seemantasaha** [comment]
W18 OK. 100 points.

**Comment by seemantasaha** [comment]
Resolved.
