### ISSUE TITLE
Powersave will turn off functions of the phone to save power. 50 pts

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-android-smoke-signals#4]
Text //Powersave [function name] to turn off the function. List of functions include:

Turn sound on, to vibrate to mute
Turn wifi on or off
Turn bluetooth on or off
Turn NFC on or off
Turn all of the features off 

~50 points for each function

W16 ok!

**Comment by Tektonbuilds** [comment]
F16 OK (50 pts)

**Comment by thatonesimon** [comment]
Should this feature only allow users to turn off settings? Or be able to toggle them? 

Suggestion: Instead of having the user have an "all" command (//Powersave all), turn off all features if there is no argument (just //Powersave).

**Comment by Tektonbuilds** [comment]
Well "on and off" means toggles but if you're going to take on this project, your suggestions are basically to yourself. If you want to "//Powersave all", go ahead. One of the things you should think about is how to get each of the functions to work and then group them. Don't do everything at once.

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/15). Mute, wifi, bluetooth and all.
