### ISSUE TITLE
Refactor SMSRequestManager.java

### ISSUE THREAD

**Issue by lanthony159** [UCSB-CS56-Projects/cs56-android-smoke-signals#40]
The `SMSRequestManager` class contains over 500 lines of code with multiple occurrences of duplicated code and numerous return statements, especially in the method`parseSMS`. Clean up the code by refactoring the `SMSRequestManager` class.

~estimated 250

**Comment by ankushrayabhari** [comment]
#39 gets rid of SMS Request Manager in place of multiple smaller class.
