### ISSUE TITLE
Refactor Settings

### ISSUE THREAD

**Issue by ankushrayabhari** [UCSB-CS56-Projects/cs56-android-smoke-signals#48]
Currently, settings is a bloated class that couples the UI activity of editing settings with the backend of  storing the settings. Consider splitting up settings into a backend class like SettingsService and factor out all the SharedPreferences code into there.

**Comment by lanthony159** [comment]
F17 OK (200 pts)

**Comment by seemantasaha** [comment]
W18 OK. 200 points.

**Comment by seemantasaha** [comment]
Resolved.
