### ISSUE TITLE
Check phone service statuses. 100 pts

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-android-smoke-signals#5]
Text //Status [function] to find the status of the function. List of functions include:

Mobile data? (might not have permission in new versions of android)
NFC
Return status of all function statuses Estimated: 50 -100 points each
Compile all the status functions like //Wifi and //Bluetooth into a single //Status function to minimize code. ~50-100 points depending on time spent

W16 ok!

**Comment by Tektonbuilds** [comment]
F16 OK (100 pts)

**Comment by jimmylle** [comment]
Fixed in this [pull request](https://github.com/UCSB-CS56-Projects/cs56-android-smoke-signals/pull/22).
