### ISSUE TITLE
Fix //Ring. 100 pts

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-android-smoke-signals#6]
It should say 2 minutes and then stop ringing as soon as the user interacts with the phone (hint: use Intent android.intent.action.USER_PRESENT) ~100 points.

W16 ok!

**Comment by Tektonbuilds** [comment]
F16 OK (100 pts)

**Comment by ankushrayabhari** [comment]
#39 fixes this by adding a new screen that allows you to stop ringing.
