### ISSUE TITLE
The app does not recognize phoneNumber from Whitelist

### ISSUE THREAD

**Issue by BrianEKim** [UCSB-CS56-Projects/cs56-android-smoke-signals#60]
I realized the message "//Ring" was working for the Stimulator; however, when we ran it on my phone it did not work. We matched it exactly like we did with the stimulator shown in the picture below but it did not work.
<img width="358" alt="screen shot 2018-03-06 at 6 06 32 pm" src="https://user-images.githubusercontent.com/26912769/37069656-2e69955e-2169-11e8-9f0f-aa72d16573bd.png">

First I added an Android Debug Database(very interesting), which allows me to see all my databases, directly edit the values, sort data, and look at the entity value themselves (basically see my room database on a browser online). This allowed me to first check if the data was on the Whitelist. I made a few fixes to the Whitelist to get all the values to show up, but it was not the actual problem.  
Now I determined it was the validPhoneNumber method and used a Log.d(body, phoneNumber) to see what phoneNumber was being compared to the numbers in the database. I realized this was a formatting problem. We want the numbers in the database to be in form +1(rest of the digits). So I changed the WhiteList activity to show users how to input numbers.

**Comment by seemantasaha** [comment]
W18 OK for 50 points.

**Comment by seemantasaha** [comment]
Resolved.
